name: cicgreenloan
description: A new Flutter application.
module:
  androidX: true

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.1+43

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  # firebase
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  firebase_core_web: ^2.0.1
  firebase_crashlytics: ^3.0.6
  firebase_dynamic_links: ^5.0.7
  firebase_messaging: ^14.1.3
  firebase_messaging_web: ^3.1.0

  # State Management
  get: ^4.1.4
  rxdart: ^0.27.3

  # Route Management
  go_router: ^6.0.2
  beamer: ^1.3.0

  # Network Request
  dio: ^4.0.0
  http: ^0.13.3

  add_2_calendar: ^2.1.0
  animations: ^2.0.0
  app_settings: ^4.1.0
  app_tracking_transparency: ^2.0.1
  badges: ^3.0.2
  
  cached_network_image: ^3.0.0
  chewie: ^1.0.0
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  country_picker: ^2.0.18
  cupertino_icons: ^1.0.3
  device_info_plus: ^8.0.0
  
  dotted_border: ^2.0.0
  dotted_decoration: ^2.0.0
  equatable: ^2.0.3
  expandable_text: ^2.2.0
  file_picker: ^5.2.0+1
  
  fl_chart: ^0.60.0
  flutter:
    sdk: flutter
  # flutter_card_swipper: ^0.4.0
  flutter_image_compress: ^1.0.0
  flutter_image_slideshow: ^0.1.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screen_lock: ^9.0.0+1
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_styled_toast: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_switch: ^0.3.2
  flutter_widget_from_html: ^0.9.0+1
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.3
  geolocator: ^9.0.2
  google_maps_flutter: ^2.0.8
  
  image: ^4.0.13
  image_downloader: ^0.31.0
  image_gallery_saver: ^1.6.9
  image_picker: ^0.8.0+3
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.4.0
  lazy_loading_list: ^1.0.1
  local_auth: ^2.0.2
  localstorage: ^4.0.0+1
  lottie: ^2.0.0
  miniplayer: ^1.0.0+2
  modal_bottom_sheet: ^3.0.0-pre
  new_version: ^0.3.0
  number_display: ^3.0.0
  open_filex: ^4.1.1
  page_view_dot_indicator: ^2.0.0
  passcode_screen: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0
  pretty_qr_code: ^2.0.2
  readmore: ^2.1.0
  
  screenshot: ^1.2.1
  share_plus: ^6.3.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  showcaseview: ^2.0.0+1
  slide_action: ^0.0.1+3
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.0.0
  sqflite: ^2.0.0+3
  syncfusion_flutter_charts: ^20.2.36
  syncfusion_flutter_gauges: ^20.1.56
  syncfusion_flutter_pdfviewer: ^20.1.56-beta
  table_calendar: ^3.0.0
  # upgrader: ^4.4.0
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0
  video_player: ^2.1.5
  webview_flutter: ^4.0.2
  webview_flutter_android: ^3.2.4
  webview_flutter_wkwebview: ^3.0.5
  youtube_player_flutter: ^8.0.0
  flutter_swiper_plus: ^2.0.4
  flutter_native_splash: ^2.2.7
  focused_menu: ^1.0.5
  flutter_expandable_fab: ^1.7.0
  mobile_scanner:
    git:
      url: https://github.com/umkithya/mobile_scanner_pro.git
      ref: master

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Logo/cic.png
    - assets/images/notificationicon/
    - assets/images/svgfile/backgroundSlide.svg
    - assets/images/svgfile/
    - assets/images/
    - assets/images/banks/
    - assets/images/wallet/
    - assets/images/banks/bank_transparent_logo/
    - assets/images/reviewImage/
    - assets/translate/en.json
    - assets/translate/kh.json
    - assets/images/flag/
    # - assets/pdfFile/
    - assets/images/slide/
    - assets/images/svgfile/menu/
    - assets/images/Logo/
    - assets/images/learningPlatform/
    # - assets/videos/make_money.mp4
    - assets/images/animation/
    - assets/images/privilege/
    - assets/images/morePopUp/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500

    - family: KhBattambang
      fonts:
        - asset: assets/fonts/Kh-Battambang.ttf
    - family: KhKulen
      fonts:
        - asset: assets/fonts/Kh-KoulenL.ttf
    - family: SFProDisplayBold
      fonts:
        - asset: assets/fonts/sf_pro_display_bold.OTF
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  image: assets/images/splash_screen_logo.png
  color: "#ffffff"
  android_12:
  android: true
  ios: true


flutter_intl:
  enabled: true
