@baseUrl = https://cicstaging.z1central.com/api/
###

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNDUxN2FmYTU1ZTI0YTA5ZWI0NDI1MjA2NGQ1MzBlZjg5ZDY0NTEwYWY2NGJkZDE0NzI3NmM3YmEzZTQyNDI3NzNlZmUxMWU3ODAzNDg4YjkiLCJpYXQiOjE2NzI1NDk0OTguMzA0NjkxLCJuYmYiOjE2NzI1NDk0OTguMzA0Njk1LCJleHAiOjE3MDQwODU0OTguMjgwMjkxLCJzdWIiOiI2OCIsInNjb3BlcyI6WyIqIl19.CF0ntPQ9VIrrimUWwhkPzghC_Btki7Z896KGH5UjwX_EsQVCkB0J431m1brK5bREqW0Upcr-5qNRVMDj_yxFu9ECR_2X5pT5vqbOBBdpG6sKftjYpvyX5vImclACDFZkT4W9ZIS7OnQ-Itlwa5Q4Su3a3DpWIZzzKTlSNdld1hTwqGwOi16moDmDBte9mu30ugiu3Y2qtFkrKq3ZhRpkK-2DjLBKOM3RSpVjxUkdchKCtUXyh0KuuJc5OXXiG_7qHBzKXE4tLys8xF40CNCKTYh-pcvAB-ENMuDTkmO2T3MsDOcdYV7wkkIjPn2dfNlhs0wPdU0CcXaSEQW5nSqWoF7am53JkbK_1pm2V8lnM5Lt65DUkllRcevVyEvyubMLhJCt0lk5mXGQDZ_xn26iquybrEypIPpuJDObsXO_u6Hbe3mI_n2nANATEwzsI9vVrvs5zHe6InwTRsql6TkL8RFMEgyn_5Yqq6nrkOaeQ4M-XkUaakaHezPcZ4Gz0297dknPf8US_6DkCvgWlZha0WYe4ugMVSppKibjbOU5nxVhThJnTNc_3ex8iEdocNUYjqM4fXDMPihpSWn3HeTL04XwgPEfQi1Yvxcr7vMHGyoCtcPhZREoRbYUXflRhwpHS-0qn0nk0HLXE9hsXUh3hgNdHFvjoAKxcyaghKMIXfk
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+855975431111",
    "password" : "SrunTola@2022"   
}
###
GET https://cicstaging.z1central.com/api/v3/event-view/ticket?event_id=14
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{baseUrl}}v1/user/notification
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/app-setting
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/slide?type=Splash Screen
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/support
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/ui?name=APP&type=paragraph
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/ui?name=APP&type=paragraph
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}