
@baseUrl = https://cic.z1platform.com/api/v4/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiZDJjOTNkZWZjMmIyN2MwYTE0ZGU5Y2QxODEyZDI0MmFjNzFmNjBkYzk3YTk3NWIwNTM1ZTdlYzFlODdjZjAzMTBhMGRhMGQ2MDIxYzljNjMiLCJpYXQiOjE2NzQ4MTA5ODEuODUzNDgsIm5iZiI6MTY3NDgxMDk4MS44NTM0ODMsImV4cCI6MTcwNjM0Njk4MS44Mzk2MTgsInN1YiI6IjM3MSIsInNjb3BlcyI6WyIqIl19.Kbt3JPpgfE_k9RLiyB5h-nE_t6sbxeGKp3ez7lfy9shshMUKzVFA1nkDiQ7KC8LXscVAIzUCpWbNTnJWeU0neum4UgiEk3FBaK9sHkYJAOXq34069XTebEK8DgHdwugl5iiVAAtRX9LpADrOhwDoV13bmApraNC_y8Fjf0Epte8LJufp7D6k_Laj_uA3dRMlNuAXJlHDP8yDTDcI82tQBrOVF6to-nv_bRANt36xa7xauP8XImn042wYF3ZaCLBuIZyTZVPOQyyHrRZXgVoeP6b7fnjMqpwcYFMxGgNI5Az0nfi6RYnyDoF08U-hTalvB0sf1wQSzQYW7vpA634kDjfe5hbe-GlvP_GwiZoEk1jXPaK8TNKZmld4uhFPyeBRmGbGuPXxXevcaV3DHQCIOaTtwK7ICoqEPcA0gzCyhlmAn_MYYiR16ONO7k8GERzY53X2XyzqME6X8bHGpmsY7purb2zNWgv9IL7Y4pzzLhMRqEYCFLH46f6VMqMS0sFhO3cRm859YnELL8Z-aqd9Eh8jzPjoKGW_DBLXZEIqgc4V67UGVh-djVwAr-UuALPpnXUYvPwXVgLGbZFunAYO73ah1rrwMAHsaHkvZC7Aqepbgb2XkcEGoy0wDnJ_GXZMc59zB2Jt1YDmTjbCwRmRZ9FTQj6qdqUyCqKtWXm8jek
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+855975431111",
    "password" : "Admin@2023"   
}


###
GET {{baseUrl}}slide?module=privilege
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}service/qm?partial=menu
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/technical/support
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/ui?name=APP&type=paragraph
Accept: application/json
Content-Type: application/json


// menu-i