
@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiY2Q4YTE5M2MwMWY2ZGQ4NjI2OTY5MzQ1M2FhODEwMTFhOTVhNDM1MDQ3Nzg0YzUxOWFjZGJhMmM2Y2JmMDcxYTgxMDU3YzdkMTlhZjQ4YjEiLCJpYXQiOjE2NjU0NzQxMTAuMjgwNjU2LCJuYmYiOjE2NjU0NzQxMTAuMjgwNjYsImV4cCI6MTY5NzAxMDExMC4yNjkxMTIsInN1YiI6IjEwIiwic2NvcGVzIjpbIioiXX0.C4MDkw5vpT_p-WhploGY-kv8t8KN_M8L0Zt1xS_E2eT934H6AGFDuexJ3JtsjFuB1xLfAZFKtb3pypAL7Bq5kHph_Xd7U6_1L7dxPDKXLLOIWzrqXm_zzPGG1QaAIfRCDQEFSVDukoGiBBJo4q4vE1UBXx8DfjZqXo-JBJJJ3H0qTllyLjJ_4CPpwJ_Z7_5zryvJNSECXS_HqM--QD8Kb6GxwqQebLytLV02BtK2Bo96dkp8c0dYP_tbzQHiHxNI9GCSbJPFuDJT3vs89Co-4y0LpfSlKZ7PAYsMZI2qJUc4cnzu7kZ1aM90lTExprj1bgzvFhHK5FHDAabS-dQYliODZvSQmwFv_lw6gc2VOa76vNMNlb8F3mPWIR_ogJox9IcVbA-5AyEhnh2yZgYIvQO_7_2rc2iZXMEgZu9xHC_u8ThdH_XiFSJnjGfx7Lrs63TRwDwL3f65y6IRrnzLZ9-jd6rEAWdILuYZSJ8M19PLVcHbsZ6sp6__0_ihl-vu5j4NSFDwcAc_wwpjRGX39DqDmOKlZQXAigu-gTAPwMd8IL5XemMiNIsPV_0fetbpjpGbPjpWlR-cmYcLl__iEQFk7ptSPzdGUhL83KGD2ZNaU99EECKqqb103lVb_0Zo1VLMXwedXAX0QTEXfL-b5U1MrVOjkYA_Q3FAm3e2-iA
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305096",
    "password" : "Admin@2022"   
}

###
GET {{baseUrl}}v3/app-setting
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/technical/support
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/ui?name=APP&type=paragraph
Accept: application/json
Content-Type: application/json


// menu-i