@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiYTA3MjViNTVlMjE2YTQ1ZjdhNWYxNTlhYmI3ZGU0MzNiZWY5MDg0ZTk3MzllYjE4OTkxYmE4ODYyZDNhOTBmODkzNjc0NjEyMDIxMDNkMTQiLCJpYXQiOjE2NzY1MjMxMTMuNjc5NTg5LCJuYmYiOjE2NzY1MjMxMTMuNjc5NTkyLCJleHAiOjE3MDgwNTkxMTMuNjcxMDYsInN1YiI6IjgzIiwic2NvcGVzIjpbIioiXX0.h76bxJIz8xWuTE_AIfWqQYtdCWZWgy0RCzPmjb89fzWfVmO3YcIqmw5IRPvKoOPAaFZeNwWOOIc1A4AnpmasUF7TDyR2brOfgQbm4QgA7hC3fJ9Uvy3KP3Z6jUvNGlXNpw7YNnYFRPX89CvRUbv6UWXo00SpEprYNuY4ktvV_zQAdHZfQO2-9fzLs_skv177y3MGYBeGfcIRVVTrQcYgan6VgKKAZbVQ58COdHOJ6VaixqXgcTTpBDZIN1wFXEDhW3o5SHT4y5f_IHabBg4td78hTTYfpCfGS2m0esLV1wyBnnMv7dwm6ov4nPWGqzztpG6xBvstCT1VKNfo44lj_HInfTMJCqRfUDsetJQJfWR6Z7haXVHXf43YJa_0wyNrRwr96nbWJXqoLI4CrA8qLKz8TAu-5JNfXtWHtq30ntC9v6Fe_hFLIpZJLf-EtT-k6n7DKHZKbgEOm-1b2ikYdZyWK31qAu6VVL_qvidJTMWLM7z2QDAt3L9l6qBw4E1HSazohRwfLGeKyX-9-Vc6rDeIMRCTyW5qP2Dbn3cBbOZZNhwMB3MnA_RxlVr7HhItoQ58FFiXB-dWmN44bBVanxF9l2FoTaXGOv37bLzfZoGxjCWvsWSF1m82b4VITbmMWJ9CUe2v0Xq6zWTsV7tuFgRajfeBofD_WkkRYCBfTug
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305096",
    "password" : "Admin@2022"  
}

###
GET {{baseUrl}}v3/return-on-investment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/wallet-available-balance
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}v3/cash-out
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount" : 13000,
    "bank_id":12
}


###
GET {{baseUrl}}v3/history?type=all
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/history?type=expense
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/history?type=income
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/history?type=cash-out
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/history?type=cash-in
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/history?type=cash-in
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/history?type=subscription
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/history?type=cash-out-cash-in
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
get {{baseUrl}}v3/bank?member_id=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
get {{baseUrl}}v4/bank-type
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
get {{baseUrl}}v3/bank?type=UT-Subscription
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{baseUrl}}v3/create-bank-account
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{

    "bank_name" : "ACLEDA Bank",
    "account_name" : "Horn Chhany",
    "account_number" : "002480960"
}

###
POST {{baseUrl}}v3/subscription
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

{

    "number_of_share": 560,
    "number_of_share": 2000
}

###
get {{baseUrl}}v3/price
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
get {{baseUrl}}v3/ui
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/subscription
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/subscription-summary
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### 
GET {{baseUrl}}v3/certificate
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### 
GET {{baseUrl}}v3/pending-subscription-payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/qr-subscription-member?q=Chhuon
Accept: application/json
Content-Type: application/json

###
POST {{baseUrl}}v3/qr-subscription
Accept: application/json
Content-Type: application/json

{
   "is_cic_member": 1,
    "member_id": 374,
    "name": "",
    "number_of_share": 1000,
    "phone": "",
    "referal_id": ""
}

### 
POST {{baseUrl}}v3/qr-subscription
Accept: application/json
Content-Type: application/json

{
   "is_cic_member": 0,
    "member_id": "",
    "name": "Brem Brey",
    "number_of_share": 200,
    "phone": "0962533337",
    "referal_id": 374
}

###
GET {{baseUrl}}v3/live-up-trading
Accept: application/json
Content-Type: application/json

request-otp
###
POST {{baseUrl}}request-otp
Accept: application/json
Content-Type: application/json
# Authorization: Bearer {{token}} 

{
    "phone":"+85581814157"
}

###
GET {{baseUrl}}v3/user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/subscription-setting
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/bonus-setting
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{baseUrl}}api/v3/request-payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount" : 300,
    "referal_id" : 1
}

###
get {{baseUrl}}v4/user/wallet/transaction?deposit=1&cashout=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
get {{baseUrl}}v4/ui
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
