@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNjRlZTk3MzQ3OGE0ODQ4M2FlOTFhNDc1YWQyYjUxMzc2YTBkODZmMWY5OWE1Y2MxYzAzNTNlMjBkZDFkNWMxYTI1ZWFhOTQ5NGU3ZWNjZWEiLCJpYXQiOjE2NjM3NTMwMzkuNzQ4MDgyLCJuYmYiOjE2NjM3NTMwMzkuNzQ4MDg5LCJleHAiOjE2OTUyODkwMzkuNzM2MDI5LCJzdWIiOiIxMSIsInNjb3BlcyI6WyIqIl19.Ys8yq-LAeZasyJXtcMekekCsbo9XrRYVLF-cVfJ1n5asCEYDnQI0e5zC0Ahf-oCRKzgA8fPFHCrK2UHREt5sMgrsgJCGEndcAcM-qtveHBQF9mDuorg_l8-Vja6L6oIngScmQtMLEfv8sX_ai0BaSmqN3ytV-apFBCbvTXUSgJzXWVgwmPckGJUtUaNJOyKtrLM1xUUgx_m-sCLBRxL_EY0zMJ8WrUP5MAZwusQCZU0kjB9jq70yKmbygX3N4BakztnvLbSVx1Kei6bqM-UbAwPYrM2RqJUt7ctWrAYVynziYsPH9PBqK7p84v5OcCFvF7EEMBOV4Nc7-_AnJsLa7Baw5q-_m8hvS35X15ZVLpYpyX9ac7NtDkeAN5k9DRWO8lmIthbUPRbbC_9nJOtPdzUY40hVTeedVr-8XmrXJs95xCOocE3EZejgDOem4f1nsq9r-UZZVzoQgh5QdsggOqDTaV-2nyYYprVtbwDvmo0pDV1fnei_bGgOFbC2L82vmIWKbkATBD2wdqJRrXapG_i0Pdl1OLVHon2QrubD7mmDciFkozOz5R7Zu1QO5V5pgiIk6KY9Nv6vqYO49OXxSPSHBQcRucLjxYHnAWkV2mEAGAjZW4fPWQNJQaCbWDkd-IYuVWIh3wkIICD_UhnZQjGfSycEhrJQVQWi2ghrluI
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85569722942",
    "password" : "@1234567Y"   
}

### FIF Application API

POST {{baseUrl}}v3/fif-application
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "product_id": 6,
    "duration": 12,
    "invest_amount": 7896,
    "investment_date": "09-07-2022",    
    "first_payment_date": "15-07-2022",
    "interest_receiving_account_type": "BANK",
    "bank_id": 4
}

### FIF Application Pending List
GET {{baseUrl}}v3/fif-application/39?type=pending
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application confirmed Detail
GET {{baseUrl}}v3/fif-application/32?type=confirmed
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application Delete
POST {{baseUrl}}v3/fif-application/cancel/12
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "reason": "Hello world"
}

### Account Detail
GET {{baseUrl}}v3/fif-account?hide=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
### Account List
GET {{baseUrl}}v3/fif-account/18
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application Rename title
PUT {{baseUrl}}api/v3/fif-application/117
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "account_name": "Family Saving 1"
}

### Total investment and hide/unhide
GET {{baseUrl}}v3/fif-account?total_investment=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "hide",
    "id" : 7
}


###
POST {{baseUrl}}api/v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "show",
    "id" : ""
}
###
POST {{baseUrl}}v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "hide",
    "id" : 1
}
### Renew Account
POST {{baseUrl}}v3/fif-application/process?type=renew
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "investment_id": 24,
    "renew_period": 3
}

### Submit withdraw
POST {{baseUrl}}v3/fif-application/process?type=withdraw
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "investment_id": 24,
    "disbursement_date": "2022-07-05",
    "amount":20
}

###
GET {{baseUrl}}v3/investment-account-histories?investment_id=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### call center
GET {{baseUrl}}v3/call-center
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### fif bank
GET {{baseUrl}}v3/bank?type=FIF
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Principal History
GET {{baseUrl}}v3/fif-account-histories?investment_id=30
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Contract History
GET {{baseUrl}}v3/fif-contract-history?type=canceled
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### fif production
GET {{baseUrl}}v3/fif-product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Service Manu
GET {{baseUrl}}v3/service?partial=menu
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### View contract as web view
GET {{baseUrl}}v3/fif-view-contract/32
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Certificate
GET {{baseUrl}}v3/customer/certificate/download
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Notification
GET {{baseUrl}}v1/user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### FiF Bank
GET {{baseUrl}}v3/bank?type=FIF
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Service Agreement
GET {{baseUrl}}v1/support
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Submit withdraw
POST {{baseUrl}}v3/validate/principal-deduction
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "invest_amount":12000,
    "product_code": "MPD-0002",
    "on": "duration",
    "duration": 12,
    "deduction_amount": "",
 }


### Stop or enable auto renewal contract
POST {{baseUrl}}v3/fif/change/auto-renewal
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fif_id": 12,
    "auto_renewal": "no",
}

### FiF Bank
GET {{baseUrl}}v3/bank-type
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/fif-return-payment-method
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

