@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiOWNlMTRhYjcxYmY1ODRmZGEzZTRiM2EzNTY0MTMzZjUzMGUzZjJlZmYxMWVmN2EzZjcwOTYzOWQ3ZjY3ZTEyMmYzM2ViYjU1YWU5MDhmNWUiLCJpYXQiOjE2NjA3MTY1NDQuMDczNjk3LCJuYmYiOjE2NjA3MTY1NDQuMDczNzAyLCJleHAiOjE2OTIyNTI1NDQuMDU5MjA0LCJzdWIiOiIxMCIsInNjb3BlcyI6WyIqIl19.WJugkzzT_nnQxHGv3ByOMccgRqjTII5unQxKjL6f6hAY3E1dqSR_qXwD48bunckVv5-xzUf8dIAzV0VZHVHQYXl82HfUtYbN5dSSew7wSJMy3auJJiQqSbtx64S-jE1jy4jcb5FgrKfLDFA-weZk5UGc1tNhf6AAvt5OEoCBwa-BZh9I0auXxDd8VFMSe7OxOPx0H68Cy7tem2if3cGi98mesigjhqnmRLIC4mnz4fjKhGIG-UKPjhllh_yM8o05vZaV_LYSrrlFge_WCMWrloFsHtx8oNlGAnGyZ7efjlYptQStcYx1JucKGTQzK0ISohexGbbEfTfwo7FhgDHurZvj0CdxfreDHMolvCohfZ_WC1UtgSUacXcZsBk5X9YtRLu0IIEPYjHkJg6tQGMYExC26ol9jYIwldSsj4RTaehzVu0Vk1sh-FSsE6hWEaQmYu9mIRFY-AkT4lceyjRQRK5fAr45BjPbECFT98p7JCv_0JW9fZ7exWd3K2qLlLRq-7-dyPgOnPYi3tfDvfDZ5sL9JqdCAXM7237dVoadYIyjrWyxl-_RdZ23H85Xwy1-1rSleiGpeYfHki-UdxHCDHwyd11lztvOKn8Dri0oTmp5IEOFLM5TiRJFZJbOhdZ5J_Je69h0WPs68DmBCKuSnDalkMTbWy2noMePPNuCvgo
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305096",
    "password" : "Admin@2022"   
}

### FIF Application API

POST {{baseUrl}}v3/fif-application
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "product_id": 6,
    "duration": 12,
    "invest_amount": 7896,
    "investment_date": "09-07-2022",    
    "first_payment_date": "15-07-2022",
    "interest_receiving_account_type": "BANK",
    "bank_id": 4
}

### FIF Application Pending List
GET {{baseUrl}}v3/fif-application?type=pending
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application confirmed Detail
GET {{baseUrl}}v3/fif-application/32?type=confirmed
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application Delete
POST {{baseUrl}}v3/fif-application/cancel/12
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "reason": "Hello world"
}

### Account Detail
GET {{baseUrl}}v3/fif-account?hide=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
### Account List
GET {{baseUrl}}v3/fif-account/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application Rename title
PUT {{baseUrl}}api/v3/fif-application/117
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "account_name": "Family Saving 1"
}

### Total investment and hide/unhide
GET {{baseUrl}}v3/fif-account?total_investment=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "hide",
    "id" : 7
}


###
POST {{baseUrl}}api/v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "show",
    "id" : ""
}
###
POST {{baseUrl}}v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "hide",
    "id" : 1
}
### Renew Account
POST {{baseUrl}}v3/fif-application/process?type=renew
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "investment_id": 24,
    "renew_period": 3
}

### Submit withdraw
POST {{baseUrl}}v3/fif-application/process?type=withdraw
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "investment_id": 24,
    "disbursement_date": "2022-07-05",
    "amount":20
}

###
GET {{baseUrl}}v3/investment-account-histories?investment_id=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### call center
GET {{baseUrl}}v3/call-center
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### fif bank
GET {{baseUrl}}v3/bank?type=FIF
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Principal History
GET {{baseUrl}}v3/fif-account-histories?investment_id=30
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Contract History
GET {{baseUrl}}v3/fif-contract-history?type=canceled
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### fif production
GET {{baseUrl}}v3/fif-product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Service Manu
GET {{baseUrl}}v3/service?partial=menu
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### View contract as web view
GET {{baseUrl}}v3/fif-view-contract/32
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Certificate
GET {{baseUrl}}v3/customer/certificate/download
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Notification
GET {{baseUrl}}v1/user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### FiF Bank
GET {{baseUrl}}v3/bank?type=FIF
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Service Agreement
GET {{baseUrl}}v1/support
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Submit withdraw
POST {{baseUrl}}v3/validate/principal-deduction
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "invest_amount":12000,
    "product_code": "MPD-0002",
    "on": "duration",
    "duration": 12,
    "deduction_amount": "",
 }
