@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiYTBmMjcwY2ZmYmIxMzE4NjlkZWU5NDgzZDZhODVmYTI5NjkyOTUzZmQwZmI5MTYwNzc1ZWRjYjk3MjMwMmRjODAyNTA5MzYwYTNlZWE5NDgiLCJpYXQiOjE2NjE3NDU0OTQuNzk4MSwibmJmIjoxNjYxNzQ1NDk0Ljc5ODEwMiwiZXhwIjoxNjkzMjgxNDk0Ljc4ODM4LCJzdWIiOiIxMCIsInNjb3BlcyI6WyIqIl19.m4oXNo63fsB3YElnBdE6jZtJtIF371JyKhT8-FMzxVaE_rULi9NoARBrvPzvhhAsngu2SH4xwxaQWh2foxKowfj1AcKkH1KqMSwWeerLjL8fSDXhac_ALjkDxGmjQxqupJl2tuGKDS6PXvkMvBk6lgC79HJL-NRO8VI7LqjawPKbxbAA3iTvsLHDqejYxmDG6wZ8hwVG16T4Ox8cFMyeSK4HYytpPFGiVgNvuGBNpzhSGquLx_yNo8y_wOn5G36tZwgm0P9FxvlXntVQzqUmx3tWeI8M6aoNeAOhZatFuG0SjgdyOgGxXArB2dcKTLlbYznuASAPs3KC0fBChpC05sZuO1SSYzNCpPxhmYEWGqcASG7-LceBf0pKjbw5kHkeOuS9X96XH5XM-Xr2w0d2fMyJZHVyBoSliM6wDtmHCEHSSPGZQtybi4Kn2UJNYolzGxkyPv6mTNgXXI9Q5Nhx_vfDOVWhoRTuaQbcOibdiVdlq8hiBM9dkK9QMcvj8eyEMxzD6I49GZfI62WwesUh69tAV6Y_BP_mJrKtwhX718V0zuJfEgbkxJtZ7k8KvxrP2Y9WJIAt9QrMwBwSwZwMNBtlKDynJ3vyoouKGlZIoQ9xSm5DpgANfXB66FVLTh1YHMM0lP2eABkYNxQ9pxeInvZZHGBYYlz4bqLJdyRJZkI
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305096",
    "password" : "Admin@2022"   
}

### FIF Application API

POST {{baseUrl}}v3/fif-application
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "product_id": 6,
    "duration": 12,
    "invest_amount": 7896,
    "investment_date": "09-07-2022",    
    "first_payment_date": "15-07-2022",
    "interest_receiving_account_type": "BANK",
    "bank_id": 4
}

### FIF Application Pending List
GET {{baseUrl}}v3/fif-application?type=pending
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application confirmed Detail
GET {{baseUrl}}v3/fif-application/32?type=confirmed
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application Delete
POST {{baseUrl}}v3/fif-application/cancel/12
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "reason": "Hello world"
}

### Account Detail
GET {{baseUrl}}v3/fif-account?hide=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
### Account List
GET {{baseUrl}}v3/fif-account/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### FIF Application Rename title
PUT {{baseUrl}}api/v3/fif-application/117
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "account_name": "Family Saving 1"
}

### Total investment and hide/unhide
GET {{baseUrl}}v3/fif-account?total_investment=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "hide",
    "id" : 7
}


###
POST {{baseUrl}}api/v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "show",
    "id" : ""
}
###
POST {{baseUrl}}v3/fif-account-hide-show
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "hide",
    "id" : 1
}
### Renew Account
POST {{baseUrl}}v3/fif-application/process?type=renew
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "investment_id": 24,
    "renew_period": 3
}

### Submit withdraw
POST {{baseUrl}}v3/fif-application/process?type=withdraw
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "investment_id": 24,
    "disbursement_date": "2022-07-05",
    "amount":20
}

###
GET {{baseUrl}}v3/investment-account-histories?investment_id=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### call center
GET {{baseUrl}}v3/call-center
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### fif bank
GET {{baseUrl}}v3/bank?type=FIF
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Principal History
GET {{baseUrl}}v3/fif-account-histories?investment_id=30
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Contract History
GET {{baseUrl}}v3/fif-contract-history?type=canceled
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### fif production
GET {{baseUrl}}v3/fif-product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Service Manu
GET {{baseUrl}}v3/service?partial=menu
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### View contract as web view
GET {{baseUrl}}v3/fif-view-contract/32
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Certificate
GET {{baseUrl}}v3/customer/certificate/download
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Notification
GET {{baseUrl}}v1/user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### FiF Bank
GET {{baseUrl}}v3/bank?type=FIF
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Service Agreement
GET {{baseUrl}}v1/support
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Submit withdraw
POST {{baseUrl}}v3/validate/principal-deduction
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "invest_amount":12000,
    "product_code": "MPD-0002",
    "on": "duration",
    "duration": 12,
    "deduction_amount": "",
 }
