
@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiZGMzNTY2YWYwODQ3YTkwZjI0NjMyODA2YmQ0MDdiMGYyNDk4MjhhMDdiNmVkNWEzNGU5NTAzZGJmZTNmNDYwYzAzZDc5MTY1MGQ4OTA4ZmIiLCJpYXQiOjE2NzU4MjI5MjYuMjUyMzYxLCJuYmYiOjE2NzU4MjI5MjYuMjUyMzY2LCJleHAiOjE3MDczNTg5MjYuMjM1NTU2LCJzdWIiOiIxMSIsInNjb3BlcyI6WyIqIl19.LayLGJcTNlAoBpGoVs8y_3Fc5I79UFH9N7hEaKeK9VkxRdALJT2MHSJRMtHbLLjkY48gIjkjNYIuAdAFSMguvnUrG1xrZifDBElmNvo2mON0xEvkBpoZsnfh7D0H8Iut8X3yHADIGuKASzvViLKU6ZntsH-qhL4YzGKBta7leF24__srRyi-62p1cgK2goX6LGRhxEj2uwJsl-DaV_kKWYElP1vx6kwwlbT4QcXhAxmdyA8DkNOv_48nRD9eC4QCRCMh-XGC65XG26BI-vsuzgXqlkjvVhVx4pbrT3ZzXbqmLez1glkTVVackDMwBy5RRMAnJ8vIm2ZYVvLC-Add3Gj5PPxKozVRcBdp5i4npq4bG28jm5ZQObw6kjEQD9iWgAstj0XzsqgTsGM8PiBxi5YiskCyA_riXwARWmweyZqlKMWM1KmL0ptpwy9ubXFruyzPlHU-ZRdwXOoD_1VPpuB5QlRZqhOiEn2U_cDfklTdRo_PO_gFOs-YrZTecj5k5nCYtJHVTBMKpZIE4gREPf_Qgmy-_5Kqr8ufTQjtMf8XJ-ncW41nXohXhRu39SZy8xbO-Ki1naavvdfRxwjNkFFnXSXGs-PPW9BYiRi24onw6mP8j_nWRz4GiCxBOxQoNOVwM9kwojqFZmxWfSn2ftES6foBSInYyPWLkaXbO8k
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305096",
    "password" : "Admin@2022"   
}

###
GET {{baseUrl}}v3/event?member_id=21&posted=upcoming&type=new
Accept: application/json
Content-Type: application/json
Authorization:Bearer {{token}}

###
POST {{baseUrl}}api/v3/event/check-in
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "event_id" : 6,
    "member_id" : 21
}

###
get {{baseUrl}}v3/event/25
Accept: application/json
Content-Type: application/json
Authorization:  Bearer {{token}}

###
POST {{baseUrl}}v2/event/interested/34
Accept: application/json
Content-Type: application/json
Authorization:  Bearer {{token}}

###
GET {{baseUrl}}v3/event/23
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/event?member_id=21&posted=past
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v3/event-registration?event_id=19
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/event/registration/17
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{baseUrl}}v3/event-registration
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "event_id" : 23,
    "member_id" : 27,
    "invite_id":
        [
        21
        ]
}

###
POST {{baseUrl}}v3/event-registration
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "member_id" : 16,
    "event_id" : 25,
     "guest" : [
    {
        "phone_number" : "098765434",
        "participant_name" : "yyff",
        "relationship" :"1"
        },
        {
            "phone_number" : "09876543444",
            "participant_name" : "rrss",
            "relationship" : "2"
        }
    ]

}
    
###
GET {{baseUrl}}v3/event/guest-register?event_id=20&member_id=21
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/chec
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}