@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiZjk2ZTkwNzUxYTIwZjdhYWZiMGZjM2JiYTY5ZDNmMjQ0NDI2NzI1NTcyNzNmYTMyMzI0ZjcwMTlmYzk4YjRjN2FiOGYyM2VlYzJiMjhkMGQiLCJpYXQiOjE2NzI1OTg1NzcuNzE0MzA0LCJuYmYiOjE2NzI1OTg1NzcuNzE0MzA3LCJleHAiOjE3MDQxMzQ1NzcuNzA3NDk5LCJzdWIiOiI2OCIsInNjb3BlcyI6WyIqIl19.iY1tgPQKvAj3Wbf6b1MCUfcZsjwn-TyqZlLoN_2o4eD5xDi-MBiTr7cOcM0oAljQ-tc7y80N-GyTP6TJy2UPV4MJr7C-H0wHmH8L-5zGExGaqfeuiRZIkDNUUoLm2mSc6yGqId3JsNFfo7E3J7OqHG1dUhjSP5dD1lCkXgAynAEiUPzkYbHwekOqoia41P9qwmDmuk1vOS7XLSIdKJ4eQG43rA6O69ePmzse6mc76-sTjjEXliC-fg9IvlJ_Z26f1DgcM-2oaSOfhdqxjDZDQuvHQTREdXBV0n09xqChNly559T56VTHIWk3K2giYSq7dv--GXsAahR0Lc1Fld_pKDLfXwx7XfxnaIBX59cd_6mARSL_Pr5qVww1xg_B7xL8tvkgCWRgS5n_USUtra5-ukcxEmoNGosi28WGLs_QRPmuP2KIgQEKqjzyt-FXZjhdXeF1bBG2iItOncWoaWw70ugqfO6OUiFrrOz5TmSYpq_rChNJ14q0bIXDO_LsF35njv98Nr12JJMwkK0mDJM5gCJ7IvGuahZYMm7SE8FL3whXxno_8G1qqUhwUEYoxwQL0HHZSEpGCn_NMDDmWuaCcg3-XpFTZpySgUcD4_ZY_N-aJmMgginItQjupAL-XqexaSsb3iqt_lulLB-yEausaFxjAQUMS5e_5j-JgaAo6Gg
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+855975431111",
    "password" : "SrunTola@2023"   
}

###

GET  https://cicstaging.z1central.com/api/v4/slide?module=privilege
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

GET  {{baseUrl}}v1/option
Content-Type: application/json
Accept: application/json