@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiZDU1M2M2MTUyOTQ1YWQyNjVhYzA1OTUwZDMzM2Y4ODBhYTAwOGU0MTg2NjM0NzJmYzNhNmE2YzFmMDA1YTg0MWZhMzNiNTI5MzBkMDU2NzQiLCJpYXQiOjE2NjI0NDkxNjMuOTY2NTIzLCJuYmYiOjE2NjI0NDkxNjMuOTY2NTI1LCJleHAiOjE2OTM5ODUxNjMuOTUyNzEzLCJzdWIiOiIxMCIsInNjb3BlcyI6WyIqIl19.QGcTdGy21xquFzx-12iOtUvbvJoHfF235FgkKWT1O9imFyBD88XZF-EpCJtxRHoZrcMCqpehp7X1HsfRYeqnFbdHjEEbZw6aqlSLBqII-c0KCVhPHDP6H5yQTr30qoZqCeMvVuOSXXtxFIZP0VU_A3n8OkAuSgqM3-c8qEnyMH56MIaqowRhm0ywk2TstUrZLpzpV58ViEMR7gY4SvmKJnxBuoxW11PMbz919zyZgXOxmsOe21x9Gq7CQGd9lw-wW9hzf7VsYsF7cnszdyeyjKnDrvelE9prYOKdtcvjauJCludI-f4Jx_PEPzxSzTmaC3IVinKISOXnnZzZTc-r7qAYDlq4gMRaUsv8ni6xeb_DcoJW0z0bD6daqsXQ-7CBaEnNzwuXmtbGIuO-HUilniogmrhhp-DxjE_px1dBlt43MR-XDmUE_he8T8t2X9DM7zjdjUrqMryGLLrJcQ0d6E3CjkOBht6EaIe84vrggQN6yh8TUrppo7cpN70B1VbqcKv4KeWk_jfgeowhi0uVA8brnJjaFlpMFgVqANWEy-NMmnJd5fqYGFBDf8HLmwTQIOtdto5DvsmKEeMxFz7u_x1hA6jJNR9nVw6cBixSUS_d0AIdWSi94uynZxnUWadMKv1-NGKCW5U6DzG5soSoiho8CuJxHmSKDizIDZxhXdM
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305096",
    "password" : "Admin@2022"   
}

### List all province code to filter shop
### Or v3/privilege/address/code?type=province
GET {{baseUrl}}v3/privilege/address?page=3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### search global shop
GET {{baseUrl}}v3/privilege/global/search?name=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Favorite or unfavorite
PUT {{baseUrl}}v3/privilege/shop/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Filter
GET {{baseUrl}}v3/privilege/filer?location=10,11,16,14&category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Category List
GET {{baseUrl}}v3/privilege/category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

API Privilege:

### List All Active Shops
GET {{baseUrl}}v3/privilege/shop?page=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Shop Detail
GET {{baseUrl}}v3/privilege/shop/8
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### List only favorite shop
GET {{baseUrl}}v3/privilege/shop?favorite
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Privilege submit payment
POST {{baseUrl}}v3/privilege/payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "shop_id" : 8,
    "amount" : "1000"
}

### Privilege submit payment
GET {{baseUrl}}v3/privilege/payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### favorite or unfavorite. is_favorite is boolean
PUT {{baseUrl}}v3/privilege/shop/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "is_favorite": 0
}

### favorite or unfavorite
PUT {{baseUrl}}v3/privilege/shop/3?is_favorite=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

