# @baseUrl = https://cicstaging.z1central.com/api/
@baseUrl = https://pre-cic.z1platform.com/api/v4
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNjRjOTBiN2JhZjNmYWM3MmU5NTIxNDU0MjBiMzJjYTZkNzgwZDhiYjg2NGIzMzVlY2JkZmZiMmVmZTY5MmQxZDg4NjFmZmI4OTY5MGIxODEiLCJpYXQiOjE2Nzc2Mzg0MTguMzQ5NzIyLCJuYmYiOjE2Nzc2Mzg0MTguMzQ5NzIzLCJleHAiOjE3MDkyNjA4MTguMzQwMTk0LCJzdWIiOiI3NDciLCJzY29wZXMiOlsiKiJdfQ.LLOb91KRNSBqT3HlW947E92D8DzSNkddVyL3Ray4s3xld_h-vmMqw_z0WXtdtLF25E0wkBvHkIzjF1RalQb5mcnEU60zwh5itnpMklrFlYZh7Qc94lJoB9y9yfOdmgw5YW5F0mx8hveLiwh7FCHmKbtzcvKYs5P7IYVKVttaDsMs-a5ZGSW9yTJOMeQ7sNRla3hlZ98V9Ir48XKdNVPGIwqsGuxH8mhK9BUtGCiwG0dls62KADtMabx0tp1BX911e_mjI2WLjvjXGlpKDXTmGF8S6ifp4MuNjGxYonlFRyhLl3793dhPeDU4w6sgAOlFJgehKSlfWRotglsGknYU_mxX54otbX6EgPoPkH1lJQT369vxnM67m-_D0t2XJMYxvRAoiQd_DNMs8N2AcSIldPrWYRC4QiuKwU1-vDwR4n3wzB3RZVMbd2kxTnAAZ-T67cjxI_lXaCqR2KDc__Taoz41lT_uchWIcOWhrjJJcEVd1C7UOle1XaPbeweUM6Zuq5xpqPpX6aNukAXaWAY96ntdNNjOQsBZQDVWZhmG1EMw2zOCk2OQO6UIqzTtHzcD9CkaN031TyhUff4c6mT0XOUcUAtIJgBW2HnCcOL9INAUNHkVTeZGGgQVl1xG0KKf2d7fcOCXPGb9mRUvECeusQnjxi8t9mFV6MdLLjSJ4k8
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305096",
    "password" : "Admin@2022"   
}

### List all province code to filter shop
### Or v3/privilege/address/code?type=province
GET {{baseUrl}}v3/privilege/address?page=3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### search global shop
GET {{baseUrl}}v3/privilege/global/search?name=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Favorite or unfavorite
PUT {{baseUrl}}v3/privilege/shop/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Filter
GET {{baseUrl}}v3/privilege/filer?location=10,11,16,14&category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Category List
GET {{baseUrl}}v3/privilege/category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

API Privilege:

### List All Active Shops
GET {{baseUrl}}v3/privilege/shop?page=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Shop Detail
GET {{baseUrl}}v3/privilege/shop/8
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### List only favorite shop
GET {{baseUrl}}v3/privilege/shop?favorite
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Privilege submit payment
POST {{baseUrl}}v3/privilege/payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "shop_id" : 8,
    "amount" : "1000"
}

### Privilege submit payment
GET {{baseUrl}}v3/privilege/payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### favorite or unfavorite. is_favorite is boolean
PUT {{baseUrl}}v3/privilege/shop/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "is_favorite": 0
}

### favorite or unfavorite
PUT {{baseUrl}}v3/privilege/shop/3?is_favorite=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Shop homepage:
GET {{baseUrl}}/privilege/store-home-page
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Shop branch
GET {{baseUrl}}/privilege/number-branches
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Shop list branch
GET {{baseUrl}}/privilege/list-branches
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Transaction History
GET {{baseUrl}}/privilege/transaction-history?shop_id=19
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Transaction History Filter (if filter today = today), (if filter last 7 day = last_7_day), (if filter last month = last_30_day)
GET {{baseUrl}}/privilege/transaction-history?shop_id=6&filter=today
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

