@baseUrl = https://cicstaging.z1central.com/api/v4
# @baseUrl = https://pre-cic.z1platform.com/api/v4
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiM2Q3NWRjM2VhMzEzYmQ3Mzk3MWUxNjNhM2RkYzdiMTE3YmJlOTEwNjJjY2E5MThhMGQ1ZThhMTkzMmQ0Mjk4YWMwNzMyODNmMjk3NzYzMzAiLCJpYXQiOjE2NzkyOTg4MTguMjI0MDI5LCJuYmYiOjE2NzkyOTg4MTguMjI0MDMzLCJleHAiOjE3MTA5MjEyMTguMjE0NDE1LCJzdWIiOiI3NCIsInNjb3BlcyI6WyIqIl19.pcAVeHjdp7J_vp9LSYBdGAmathuLWFIO5odtkPf8130jaMb8LFoq3nz6X6Fn7sy1sTAu9Wi3E2Y2yMKzsvnvJgNNt0Gv0ydiiuAoLnTd7adC1DjiAJYqbCOj71NQwf-B1_1dkqJk7NivPYZXMFzgLD-_22aH9sQLDSZMnprD8knHCLIGPxr-92N4auErybELk6S_x1rVY85DM0yHz4taHpMHmv--8ZfxESmo69OEWdyVq1qSmdY4w-UXS00-aNrTJQhiTXBuTTl1Bju-RD39XHh6LWmLZ4MgV_9rMcCdumP7GJCgkfvfbAVMn73Us5qqkqnGEiUTdb_sSsUo6mk5fWWIWoZEKTymcBKi_BtLrrMBfQJkcWp_eE1X5wtC_HwIpPb7HWhZ8_J7QWYJL4a7x5B8vCCxp_oWDiziIZhGEBHeVUk0ssErJJNvBd93LavzTudS9fH_Hsrfo_Af9BAnS9uuUqsr-o2Xmu761wHYE-3UG0U6VepZ8m8LtUAy_bHH-86FzVqLDaBbJC3oMbvASCS2tOpRQ0FGk0mfEv8A_ZJ1qRgpEkcA-RBgTcnNX7upgPud5YDd5B3HeaJQVxOKyCkYrJQ8D3a9Qws_avxp837WHyQK1M2NpU4ie6phaWBUSxnauqprfF-INm5hyDUaGyWavNXujobpCjkSSix8RGk
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+855963288307",
    "password" : "Boy@2023"   
}

### List all province code to filter shop
### Or v3/privilege/address/code?type=province
GET {{baseUrl}}v3/privilege/address?page=3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### search global shop
GET {{baseUrl}}v3/privilege/global/search?name=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Favorite or unfavorite
PUT {{baseUrl}}v3/privilege/shop/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Filter
GET {{baseUrl}}v3/privilege/filer?location=10,11,16,14&category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Category List
GET {{baseUrl}}v3/privilege/category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

API Privilege:

### List All Active Shops
GET {{baseUrl}}v3/privilege/shop?page=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Shop Detail
GET {{baseUrl}}v3/privilege/shop/8
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### List only favorite shop
GET {{baseUrl}}v3/privilege/shop?favorite
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Privilege submit payment
POST {{baseUrl}}v3/privilege/payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "shop_id" : 8,
    "amount" : "1000"
}

### Privilege submit payment
GET {{baseUrl}}v3/privilege/payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### favorite or unfavorite. is_favorite is boolean
PUT {{baseUrl}}v3/privilege/shop/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "is_favorite": 0
}

### favorite or unfavorite
PUT {{baseUrl}}v3/privilege/shop/3?is_favorite=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Shop homepage:
GET {{baseUrl}}/privilege/store-home-page
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Shop branch
GET {{baseUrl}}/privilege/number-branches
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Shop list branch
GET {{baseUrl}}/privilege/list-branches
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Transaction History
GET {{baseUrl}}/privilege/transaction-history?shop_id=19
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Transaction History Filter (if filter today = today), (if filter last 7 day = last_7_day), (if filter last month = last_30_day)
GET {{baseUrl}}/privilege/transaction-history?shop_id=6&filter=today
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Transaction History Filter (if filter today = today), (if filter last 7 day = last_7_day), (if filter last month = last_30_day)
GET {{baseUrl}}/privilege/generate-mvp-qr?wallet_id=002428&set_amount=200
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/mvp/balance
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/user/wallet/gift-mvp
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{   "sender": 927308932,
    "receiver": 037435193,
    "amount": 10,
    "remark": "abctest",
    "is_create_template": 0,
    "template_name": "testtemplate1"
}



