@baseUrl = https://cicstaging.z1central.com/api/v2/
@mainUrl = https://cicstaging.z1central.com/api/

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiMjNlOGJiNDBiMzg2MWQ5YTQzZjk5Y2UzODBiYzliYThkMGU2OTVhMDVlOTgyNzUwNTVlOWY3ZGE0MTI1NWEyY2I5OTM1ZjE2OGU4NDc5Y2YiLCJpYXQiOjE2MzAzOTYwMzEuNzU0MTY0LCJuYmYiOjE2MzAzOTYwMzEuNzU0MTY5LCJleHAiOjE2NjE5MzIwMzEuNzM1ODI3LCJzdWIiOiIxNTQzIiwic2NvcGVzIjpbIioiXX0.NpJ7amo5hany6Ep70SLNXP9O8Abc5XJj_EUwU6Je_a9qa0OwLs_HBHyQHd-eZAi5nTV0HKxaVhdtMIkSWBlQujRAYP5dUoeYZSF2c5aOnIf_CIhYyThO6NGcDRPt6ufjjMICTixExu5FFjrS3rNpUswpGMk5CwBzhFa6i1KIrGFDvYPxHKcvqkrFeYRDmcgxrTGMB7V4RnawIZWO0G9Sr9mSDmGhmLKdo2ItiTRyBxLRqSjuLt8HLUElRSML8UsDxNulbziR-HICmTfMFuZDA6kbWLtb7XK6KHaLh_T9KhenUvBfLFjKQtCQSty57-v3bGcv7Xr_GhxtsI8B5-1Op0Rj6uB2wv23mky-H_w3ZBib3RdTSfMvfh8E2ivgFEcOKumy5YeEmw8h7c7oHpgCwwZNtgk9RCHNDKRPZBiXBP9Uiqw8IpVGBhMhCC2wYtGFWpdPxgNHFg0NOafBwjpDPfZ_uFKWFUry56gBSnP3BFx1El5DHLtXMXCrYWXHx5Nd9w5jMNIHD3bHBPzf3K5ur8Sk_MWADLh73HvQRZ2LLyqBIVOkBH2eXxwE4OE6ofDMBY_UrM9SIzhlT3ACwK-gDaGckHHCjrYriIKgOdSDDutesh4-w3URp7mQqfhbqE34_tWtDI5IiwzyQ3Pk1JRPt6EDWfzHqJlSkv-Txhphs9M

GET https://cic.z1platform.com/api/v3/service?partial=menu
Accept: application/json
Content-Type: application/json

###
GET https://cicstaging.z1central.com/api/v3/event-view/ticket?event_id=14&member_id=46
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}trading?type=all&member_id=378
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}event?member_id=378&posted=upcoming
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}trading-setting
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}trading?type=single-trading&member_id=381&transaction_id=3685&market_id=0&operation=sell
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{mainUrl}}verify-otp
Accept: application/json
Content-Type: application/json

{
    "phone": "+61423003938",
    "verify_code": "1234"
}
###
POST {{mainUrl}}request-otp
Accept: application/json
Content-Type: application/json

{
    "phone" : "+61423003938"
}
###
POST {{mainUrl}}user/set-password
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password" : "CiCKSeng@2021"
}

###

GET {{baseUrl}}member-profile?member_id=379
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET https://maps.googleapis.com/maps/api/directions/json?origin=11.571650122647663, 104.89711736819251&destination=11.573079583465509, 104.92475484976875&key=AIzaSyCxFsYMZ51BZXTf7G4e9n78FUYT8fQHQj8
Accept: application/json
Content-Type: application/json
###
POST {{baseUrl}}event/check-in
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "event_id" : 28,
    "member_id" : 379
}
###
GET https://cicstaging.z1central.com/api/v3/ui
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{mainUrl}}v3/service
Accept: application/json
Content-Type: application/json

###
GET {{mainUrl}}v1/service?partial=menu
Accept: application/json
Content-Type: application/json


###
GET https://cicstaging.z1central.com/api/v3/ui

Accept: application/json
Content-Type: application/json

###
POST {{mainUrl}}request-otp
Accept: application/json
Content-Type: application/json

{
    "phone": "+855975431111"
}

###
POST {{mainUrl}}verify-otp
Accept: application/json
Content-Type: application/json

{
    "phone": "855975431111",
    "verify_code": "9132",
    "type": "reset_password"
}

