@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiYWUxOGFjN2RlOTc2Y2UzZjQyYTczMzViNmYzNDIwZTdhNTYyYTg3ZGYwODg1NzJhYzU0YmVkMjJmNGViMzZjOGY4Y2M0OTc3YjY5YTg5NzEiLCJpYXQiOjE2NjI2OTYxMDIuNjIzMjc5LCJuYmYiOjE2NjI2OTYxMDIuNjIzMjgxLCJleHAiOjE2OTQyMzIxMDIuNjE0MDk3LCJzdWIiOiIxMCIsInNjb3BlcyI6WyIqIl19.LiTNWSBd1DocS9zPI_93pwCfQ0F6Igk-VsCpXIWgMvlOYxQMMuPxq4wXpuYC-nWyYIx9Lm-4ovJk10YW-E2TjXtmz7wdHXlEMlUA7Y1TYuPQ3KaBBt_dYnTFqQRDhfLA_wy5Ia5a9-wFbFRDKfTeA3RlIxeKdka6rc56BgBlnhXY1YoJT_ZKFl6xqBdLDyEwIaht8tapnf9Pdy9EShSHKsKW5n7kq3V-g8Agq_LsoTg-Ugz88CPidfu81NROSXeUa07SF4IgdRyUj8EngTF0GSnLfW3Q1jymV_NIDkDKb0nNm_ZSQjdEJGxEzAkxCE-elt6uRmVMki5CSvbL0k45nVk1TP2Z-6BZoKaKbgktX7hhtot1Qa01yVANbBlHSkWHy0A_ASRzT5yWC9ZGTta52DJygYacPxEu-DLxR3_ZaHuzOMeF-sU_W8XVXfudJVOV1tgg_JbLFlAtczde6v-8MUykNsaH5pRr7dinsrM44_CHwkVXQdYPBhG6xMbno8P1DS_Z021fdQGBTzRZqSmxs1hzgjZ2JmRIDYmkgv6VBGlK9uogReqLq08CYmU_jYrAgs28MN5HQsdJAurDMM3gdbBp0xfJUIt_woMNtsVAFP7NMnFgI-4k0raxdNigppqdkmfprDkQt3rBWstgWQI2Y81L2LNZLPHeLXw1DvvSHoU
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305096",
    "password" : "Admin@2022"   
}

###
GET {{baseUrl}}user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/event?member_id=446&posted=upcoming&search=trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###
POST {{baseUrl}}v2/trading
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
"description": "test",
        "request_by": 466,
        "transaction": "sell",
        "quantity": "250",
        "price": "10"
        "plat-"
}


###
GET  {{baseUrl}}user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/trading?type=new&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=new&operation=buy&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=success&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=all&operation=buy&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=upsuccess&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading-setting
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/market
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}v2/trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "market_id" : 9,
    "member_id" : 193,
    "operation" : "buy",
    "price" : 2,
    "number_of_share" : 112,
    "description" : "description"
}

###
PUT {{baseUrl}}api/v2/trading/39
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "market_id" : 9,
    "member_id" : 193,
    "operation" : "buy",
    "price" : 2,
    "number_of_share" : 111,
    "description" : "description"
}

###
DELETE {{baseUrl}}v2/trading/39
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=success&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/trading-setting
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### 
GET {{baseUrl}}v2/trading?type=all&member_id=466
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/trading-instruction
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


########Updated#################


###
GET {{baseUrl}}v2/trading?type=success&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=new&operation=sell&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=upsuccess&member_id=718
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=upsuccess&operation=buy&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=new&operation=sell&member_id=369
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=new&operation=buy&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET {{baseUrl}}v2/trading?type=success&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/trading-video
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=all&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v1/support
Accept: application/json
Content-Type: application/json
# Authorization: Bearer {{token}}


###
# cic platform
POST {{baseUrl}}v2/trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "market_id" : 79,
    "member_id" : 466,
    "operation" : "sell",
    "price" : 7,
    "number_of_share" : 100,
    "description" : "description",
    "trading_with" : "cic-platform"
}

###
# specific member
POST {{baseUrl}}api/v2/trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "member_id" : 16,
    "operation" : "sell",
    "price" : 2,
    "number_of_share" : 1000,
    "description" : "description",
    "trading_with" : "specific-member",
    "target_member" : 14
}

###

POST {{baseUrl}}v2/trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "member_id" : 446,
    "operation" : "buy",
    "price" : 2,
    "number_of_share" : 105,
    "description" : "description",
    "trading_with" : "specific-member",
    "target_member" : 378
}

###
# cic platform
PUT {{baseUrl}}api/v2/trading/446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "market_id" : 20,
    "member_id" : 718,
    "operation" : "buy",
    "price" : 1.5,
    "number_of_share" : 101,
    "description" : "description",
    "trading_with" : "specific-member"
}

###
# specific member
PUT {{baseUrl}}api/v2/trading/39
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "member_id" : 718,
    "operation" : "buy",
    "price" : 1.5,
    "number_of_share" : 5000,
    "description" : "description",
    "trading_with" : "specific-member"
}

#Event


###
POST {{baseUrl}}v2/registration
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{"event_id":"10","invite_id":"[3, 4, 5]","member_id":" 446","name":"Horn Chhany","company_name":"","position":"Flutter Developer","phone_number":"+85510305096","email":""}

###
GET {{baseUrl}}v2/event?member_id=193&posted=upcoming&type=featured
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/event?member_id=446&posted=upcoming&type=new
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/event?member_id=442&posted=past
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}api/v2/event?member_id=442&posted=upcoming&search=test
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/event?member_id=446&posted=past&search=test
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}api/v2/event/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
# learing slide
GET {{baseUrl}}v2/slide?type=learning
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
# banner slide
GET {{baseUrl}}v3/slide?type=slide
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

GET {{baseUrl}}v3/service
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get channel by member id
GET {{baseUrl}}api/v2/channel?member_id=442
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

###
# get recommended posts by member
GET {{baseUrl}}api/v2/post?member_id=442&recommended=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

###
# view channel detail
GET {{baseUrl}}api/v2/channel/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get post(video) by module 
GET {{baseUrl}}api/v2/post?member_id=395&module=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

###
# view post(video) by detail 
GET {{baseUrl}}api/v2/post/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get more post(video)
GET {{baseUrl}}api/v2/post?member_id=442&more=true&current=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get recommended posts by member
GET {{baseUrl}}v2/post?member_id=193&recommended=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

###
GET {{baseUrl}}api/v2/post?member_id=352&saved=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/registration?event_id=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/investment-equity-fund
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=unpaid-submitted&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/investment-available-fund
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{baseUrl}}v3/loan-product?product_type=invest&option=0
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/trading-last-session
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### last trading option
GET {{baseUrl}}v3/trading-last-session
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Last trading detail
GET {{baseUrl}}v3/trading-last-session-info/113
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Notification
GET {{baseUrl}}user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get year capital gain and dividend
GET {{baseUrl}}v3/return-on-investment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
