@baseUrl = https://cicstaging.z1central.com/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNjZmZDJjZTM3MzBiNjYwY2IzYmFhOTc1Y2NkMWFmY2FmYTY5ZDgyM2QwYTllYTI5MTE0YmFmZTQyMjAyN2I5NWIwZTk1M2U1YjAwODdmYmQiLCJpYXQiOjE2NzIwMzk5ODguMDQxODI0LCJuYmYiOjE2NzIwMzk5ODguMDQxODI2LCJleHAiOjE3MDM1NzU5ODguMDM2OTI0LCJzdWIiOiI0NyIsInNjb3BlcyI6WyIqIl19.e6zXcHqdR345jpyESdc3xgWb500FlSYewP_gWkBDbAXiEHKVSLw64Lbb6-0-nRO9mVqTsB3MXFMp80WcjFOyqWHwvVYOsE8l4Msy1jPwuu0WR39qQNY4sjaQnb7LCQaipRY4PCfsdA0IFbuBlCOIPMsv4TvWkqiHVzTK90NRvJyatNvoW6e6QaU4TwVfUfS_IuZ7yKLbcfO1LWazcPe9cCzs0DgdoEgoPROvnvtSSwDReW1ubMCRyp_3oJl6lB-3gu8XlJ8d0qsePrCzF5QHhgL0_oxY--TXcXgmirgMaITLci9yWDB9LpWLKhHuW70GDAWLGbA58_5rNZPirIq0-rutlLLDNTwVDk0fGJcEe55bZq8qvsdI9Lka9FVYqTvhMhWJsZmdOgLifL-LUmaohkCHJ57-60Va6XwPv77phGMR5Cix02MRZ8gtsoG6NmYfsZalTFGBTrtgZk4GCZkWv2_azHGMeQMwNu1Y4IrOMXXurpRq3BeqPUomx9npdQo6wTHZ22ipWCgawu_A4QS5pBj9PPugqyOakNl8Aj105Vsgqe3Du2jL1N-NNjrmMjXXBKYBbJAucBo_1iIb8SIng559MrTagxdt8AB2gnZn__PCgkWqDodXjIHHBcqQqbc3rJJBH6WjPEaIq6jOz-0q6IY6B9psZUU9KfJEDCd7xaY
POST {{baseUrl}}login
Content-Type: application/json
Accept: application/json

{
    "phone" : "+85510305091",
    "password" : "Admin@2023"   
}

###
GET {{baseUrl}}user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/event?member_id=446&posted=upcoming&search=trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###
POST {{baseUrl}}v2/trading
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
"description": "test",
        "request_by": 466,
        "transaction": "sell",
        "quantity": "250",
        "price": "10"
        "plat-"
}


###
GET  {{baseUrl}}user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/trading?type=new&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=new&operation=buy&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=success&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=all&operation=buy&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=upsuccess&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading-setting
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/market
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}v2/trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "market_id" : 9,
    "member_id" : 193,
    "operation" : "buy",
    "price" : 2,
    "number_of_share" : 112,
    "description" : "description"
}

###
PUT {{baseUrl}}api/v2/trading/39
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "market_id" : 9,
    "member_id" : 193,
    "operation" : "buy",
    "price" : 2,
    "number_of_share" : 111,
    "description" : "description"
}

###
DELETE {{baseUrl}}v2/trading/39
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=success&member_id=440
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/trading-setting
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### 
GET {{baseUrl}}v2/trading?type=all&member_id=440
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/trading-instruction
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


########Updated#################


###
GET {{baseUrl}}v2/trading?type=success&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=new&operation=sell&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=upsuccess&member_id=718
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=upsuccess&operation=buy&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=new&operation=sell&member_id=369
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=new&operation=buy&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET {{baseUrl}}v2/trading?type=success&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/trading-video
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=all&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v1/support
Accept: application/json
Content-Type: application/json
# Authorization: Bearer {{token}}


###
# cic platform
POST {{baseUrl}}v2/trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "market_id" : 79,
    "member_id" : 466,
    "operation" : "sell",
    "price" : 7,
    "number_of_share" : 100,
    "description" : "description",
    "trading_with" : "cic-platform"
}

###
# specific member
POST {{baseUrl}}api/v2/trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "member_id" : 16,
    "operation" : "sell",
    "price" : 2,
    "number_of_share" : 1000,
    "description" : "description",
    "trading_with" : "specific-member",
    "target_member" : 14
}

###

POST {{baseUrl}}v2/trading
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "member_id" : 446,
    "operation" : "buy",
    "price" : 2,
    "number_of_share" : 105,
    "description" : "description",
    "trading_with" : "specific-member",
    "target_member" : 378
}

###
# cic platform
PUT {{baseUrl}}api/v2/trading/446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "market_id" : 20,
    "member_id" : 718,
    "operation" : "buy",
    "price" : 1.5,
    "number_of_share" : 101,
    "description" : "description",
    "trading_with" : "specific-member"
}

###
# specific member
PUT {{baseUrl}}api/v2/trading/39
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "member_id" : 718,
    "operation" : "buy",
    "price" : 1.5,
    "number_of_share" : 5000,
    "description" : "description",
    "trading_with" : "specific-member"
}

#Event


###
POST {{baseUrl}}v2/registration
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{"event_id":"10","invite_id":"[3, 4, 5]","member_id":" 446","name":"Horn Chhany","company_name":"","position":"Flutter Developer","phone_number":"+85510305096","email":""}

###
GET {{baseUrl}}v2/event?member_id=193&posted=upcoming&type=featured
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/event?member_id=446&posted=upcoming&type=new
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/event?member_id=442&posted=past
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}api/v2/event?member_id=442&posted=upcoming&search=test
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/event?member_id=446&posted=past&search=test
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}api/v2/event/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
# learing slide
GET {{baseUrl}}v2/slide?type=learning
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
# banner slide
GET {{baseUrl}}v3/slide?module=Slide&biometrics=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

GET {{baseUrl}}v3/service
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get channel by member id
GET {{baseUrl}}api/v2/channel?member_id=442
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

###
# get recommended posts by member
GET {{baseUrl}}api/v2/post?member_id=442&recommended=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

###
# view channel detail
GET {{baseUrl}}api/v2/channel/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get post(video) by module 
GET {{baseUrl}}api/v2/post?member_id=395&module=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

###
# view post(video) by detail 
GET {{baseUrl}}api/v2/post/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get more post(video)
GET {{baseUrl}}api/v2/post?member_id=442&more=true&current=2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get recommended posts by member
GET {{baseUrl}}v2/post?member_id=193&recommended=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}} 

###
GET {{baseUrl}}api/v2/post?member_id=352&saved=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}v2/registration?event_id=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/investment-equity-fund
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/trading?type=unpaid-submitted&member_id=446
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v2/investment-available-fund
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{baseUrl}}v3/loan-product?product_type=invest&option=0
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}v3/trading-last-session
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### last trading option
GET {{baseUrl}}v3/trading-last-session
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Last trading detail
GET {{baseUrl}}v3/trading-last-session-info/113
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Notification
GET {{baseUrl}}user/notification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
# get year capital gain and dividend
GET {{baseUrl}}v3/return-on-investment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
